### Main API Functions -----------
throwErrorWithJson <- function(type='UNK', err) { # Create the error JSON, if possible.
  if (type == "UNK")
    if (!missing(err)) { ## do we give the error object ?
      type <- "UNKE"  
      if (is.null(err$call)){  ## simple error generated by ourself, any non custom error will have a call stack
        err <- err$message
      } else {
        err <- paste0("UNK_ERR : This is an undocumented error, conact our support. Signature: ",  capture.output(print(err)))
      }
    }
  
#   # If "err" is an error, non generated by ourselves (cf above), change it to the corresponding text.
#   # Not used anymore, see the els of above, cleaner.
#   if (any(grepl("error", class(err), ignore.case=T))) 
#     err <- capture.output(print(err))

  # Create the result
  switch(type,
         "UNAVAIL" = { setStatus(503L)
                       return(createDEFAULTJson("This service is not available right now, try again later..."))
         },
         "IMPL" = { setStatus(501L)
                    return(createDEFAULTJson("The HTTP Method used is not recognized by the API. Try the OPTIONS method to get the possible methods."))
         },
         "UNKE" = { setStatus(500L)
                    return(createDEFAULTJson(err))
         },  
         "UNK" =  { setStatus(500L)
                    return(createDEFAULTJson())
         },
         {setStatus(500L)
          return(createDEFAULTJson("Unknown error type"))}
  )
}


## DEBUGGING function --------

printErrorToStderr <- function(e) {
  sink(stderr())
  cat('TRACEBACK:\n')
  sc <- sys.calls()
  cat(paste(create_traceback(sc[5:(length(sc)-2)]), collapse='\n'), '\n')
  print(e)
  sink()
}

### JSON creation functions ----------

createDEFAULTJson <- function(DATAmessage="default message - error not registered. Are you lost? You may want to use the HTTP method OPTIONS to get more information on the ressource.") {
  DEFAULTlist <- list( META = list(type = "meta - error",
                                   describing = "Contextualisation Engine",
                                   APIversion = APIversion),
                       DATA = list(message = DATAmessage)
  )  
  return(toJSON(DEFAULTlist))
}

### MISC but necessary for the well being of R -----

list <- structure(NA,class="result")
"[<-.result" <- function(x,...,value) {
  args <- as.list(match.call())
  args <- args[-c(1:2,length(args))]
  length(value) <- length(args)
  for(i in seq(along=args)) {
    a <- args[[i]]
    if(!missing(a)) eval.parent(substitute(a <- v,list(a=a,v=value[[i]])))
  }
  x
}